/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VtcHistoryRouteImport } from './routes/vtc-history'
import { Route as VtcDriverRouteImport } from './routes/vtc-driver'
import { Route as VtcRouteImport } from './routes/vtc'
import { Route as VerifyRouteImport } from './routes/verify'
import { Route as RelayPointsRouteImport } from './routes/relay-points'
import { Route as RechargeRouteImport } from './routes/recharge'
import { Route as OrderRouteImport } from './routes/order'
import { Route as InvestDashboardRouteImport } from './routes/invest-dashboard'
import { Route as InvestRouteImport } from './routes/invest'
import { Route as InboxRouteImport } from './routes/inbox'
import { Route as HistoryRouteImport } from './routes/history'
import { Route as FranchiseRouteImport } from './routes/franchise'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as BecomeRelayRouteImport } from './routes/become-relay'
import { Route as BecomeDriverRouteImport } from './routes/become-driver'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AdminExtrasRouteImport } from './routes/admin-extras'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as InvestIdRouteImport } from './routes/invest.$id'

const VtcHistoryRoute = VtcHistoryRouteImport.update({
  id: '/vtc-history',
  path: '/vtc-history',
  getParentRoute: () => rootRouteImport,
} as any)
const VtcDriverRoute = VtcDriverRouteImport.update({
  id: '/vtc-driver',
  path: '/vtc-driver',
  getParentRoute: () => rootRouteImport,
} as any)
const VtcRoute = VtcRouteImport.update({
  id: '/vtc',
  path: '/vtc',
  getParentRoute: () => rootRouteImport,
} as any)
const VerifyRoute = VerifyRouteImport.update({
  id: '/verify',
  path: '/verify',
  getParentRoute: () => rootRouteImport,
} as any)
const RelayPointsRoute = RelayPointsRouteImport.update({
  id: '/relay-points',
  path: '/relay-points',
  getParentRoute: () => rootRouteImport,
} as any)
const RechargeRoute = RechargeRouteImport.update({
  id: '/recharge',
  path: '/recharge',
  getParentRoute: () => rootRouteImport,
} as any)
const OrderRoute = OrderRouteImport.update({
  id: '/order',
  path: '/order',
  getParentRoute: () => rootRouteImport,
} as any)
const InvestDashboardRoute = InvestDashboardRouteImport.update({
  id: '/invest-dashboard',
  path: '/invest-dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const InvestRoute = InvestRouteImport.update({
  id: '/invest',
  path: '/invest',
  getParentRoute: () => rootRouteImport,
} as any)
const InboxRoute = InboxRouteImport.update({
  id: '/inbox',
  path: '/inbox',
  getParentRoute: () => rootRouteImport,
} as any)
const HistoryRoute = HistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => rootRouteImport,
} as any)
const FranchiseRoute = FranchiseRouteImport.update({
  id: '/franchise',
  path: '/franchise',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const BecomeRelayRoute = BecomeRelayRouteImport.update({
  id: '/become-relay',
  path: '/become-relay',
  getParentRoute: () => rootRouteImport,
} as any)
const BecomeDriverRoute = BecomeDriverRouteImport.update({
  id: '/become-driver',
  path: '/become-driver',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminExtrasRoute = AdminExtrasRouteImport.update({
  id: '/admin-extras',
  path: '/admin-extras',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const InvestIdRoute = InvestIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => InvestRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/admin-extras': typeof AdminExtrasRoute
  '/auth': typeof AuthRoute
  '/become-driver': typeof BecomeDriverRoute
  '/become-relay': typeof BecomeRelayRoute
  '/dashboard': typeof DashboardRoute
  '/franchise': typeof FranchiseRoute
  '/history': typeof HistoryRoute
  '/inbox': typeof InboxRoute
  '/invest': typeof InvestRouteWithChildren
  '/invest-dashboard': typeof InvestDashboardRoute
  '/order': typeof OrderRoute
  '/recharge': typeof RechargeRoute
  '/relay-points': typeof RelayPointsRoute
  '/verify': typeof VerifyRoute
  '/vtc': typeof VtcRoute
  '/vtc-driver': typeof VtcDriverRoute
  '/vtc-history': typeof VtcHistoryRoute
  '/invest/$id': typeof InvestIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/admin-extras': typeof AdminExtrasRoute
  '/auth': typeof AuthRoute
  '/become-driver': typeof BecomeDriverRoute
  '/become-relay': typeof BecomeRelayRoute
  '/dashboard': typeof DashboardRoute
  '/franchise': typeof FranchiseRoute
  '/history': typeof HistoryRoute
  '/inbox': typeof InboxRoute
  '/invest': typeof InvestRouteWithChildren
  '/invest-dashboard': typeof InvestDashboardRoute
  '/order': typeof OrderRoute
  '/recharge': typeof RechargeRoute
  '/relay-points': typeof RelayPointsRoute
  '/verify': typeof VerifyRoute
  '/vtc': typeof VtcRoute
  '/vtc-driver': typeof VtcDriverRoute
  '/vtc-history': typeof VtcHistoryRoute
  '/invest/$id': typeof InvestIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/admin-extras': typeof AdminExtrasRoute
  '/auth': typeof AuthRoute
  '/become-driver': typeof BecomeDriverRoute
  '/become-relay': typeof BecomeRelayRoute
  '/dashboard': typeof DashboardRoute
  '/franchise': typeof FranchiseRoute
  '/history': typeof HistoryRoute
  '/inbox': typeof InboxRoute
  '/invest': typeof InvestRouteWithChildren
  '/invest-dashboard': typeof InvestDashboardRoute
  '/order': typeof OrderRoute
  '/recharge': typeof RechargeRoute
  '/relay-points': typeof RelayPointsRoute
  '/verify': typeof VerifyRoute
  '/vtc': typeof VtcRoute
  '/vtc-driver': typeof VtcDriverRoute
  '/vtc-history': typeof VtcHistoryRoute
  '/invest/$id': typeof InvestIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/admin-extras'
    | '/auth'
    | '/become-driver'
    | '/become-relay'
    | '/dashboard'
    | '/franchise'
    | '/history'
    | '/inbox'
    | '/invest'
    | '/invest-dashboard'
    | '/order'
    | '/recharge'
    | '/relay-points'
    | '/verify'
    | '/vtc'
    | '/vtc-driver'
    | '/vtc-history'
    | '/invest/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/admin-extras'
    | '/auth'
    | '/become-driver'
    | '/become-relay'
    | '/dashboard'
    | '/franchise'
    | '/history'
    | '/inbox'
    | '/invest'
    | '/invest-dashboard'
    | '/order'
    | '/recharge'
    | '/relay-points'
    | '/verify'
    | '/vtc'
    | '/vtc-driver'
    | '/vtc-history'
    | '/invest/$id'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/admin-extras'
    | '/auth'
    | '/become-driver'
    | '/become-relay'
    | '/dashboard'
    | '/franchise'
    | '/history'
    | '/inbox'
    | '/invest'
    | '/invest-dashboard'
    | '/order'
    | '/recharge'
    | '/relay-points'
    | '/verify'
    | '/vtc'
    | '/vtc-driver'
    | '/vtc-history'
    | '/invest/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  AdminExtrasRoute: typeof AdminExtrasRoute
  AuthRoute: typeof AuthRoute
  BecomeDriverRoute: typeof BecomeDriverRoute
  BecomeRelayRoute: typeof BecomeRelayRoute
  DashboardRoute: typeof DashboardRoute
  FranchiseRoute: typeof FranchiseRoute
  HistoryRoute: typeof HistoryRoute
  InboxRoute: typeof InboxRoute
  InvestRoute: typeof InvestRouteWithChildren
  InvestDashboardRoute: typeof InvestDashboardRoute
  OrderRoute: typeof OrderRoute
  RechargeRoute: typeof RechargeRoute
  RelayPointsRoute: typeof RelayPointsRoute
  VerifyRoute: typeof VerifyRoute
  VtcRoute: typeof VtcRoute
  VtcDriverRoute: typeof VtcDriverRoute
  VtcHistoryRoute: typeof VtcHistoryRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/vtc-history': {
      id: '/vtc-history'
      path: '/vtc-history'
      fullPath: '/vtc-history'
      preLoaderRoute: typeof VtcHistoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vtc-driver': {
      id: '/vtc-driver'
      path: '/vtc-driver'
      fullPath: '/vtc-driver'
      preLoaderRoute: typeof VtcDriverRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vtc': {
      id: '/vtc'
      path: '/vtc'
      fullPath: '/vtc'
      preLoaderRoute: typeof VtcRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/verify': {
      id: '/verify'
      path: '/verify'
      fullPath: '/verify'
      preLoaderRoute: typeof VerifyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/relay-points': {
      id: '/relay-points'
      path: '/relay-points'
      fullPath: '/relay-points'
      preLoaderRoute: typeof RelayPointsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recharge': {
      id: '/recharge'
      path: '/recharge'
      fullPath: '/recharge'
      preLoaderRoute: typeof RechargeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/order': {
      id: '/order'
      path: '/order'
      fullPath: '/order'
      preLoaderRoute: typeof OrderRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/invest-dashboard': {
      id: '/invest-dashboard'
      path: '/invest-dashboard'
      fullPath: '/invest-dashboard'
      preLoaderRoute: typeof InvestDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/invest': {
      id: '/invest'
      path: '/invest'
      fullPath: '/invest'
      preLoaderRoute: typeof InvestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inbox': {
      id: '/inbox'
      path: '/inbox'
      fullPath: '/inbox'
      preLoaderRoute: typeof InboxRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/history': {
      id: '/history'
      path: '/history'
      fullPath: '/history'
      preLoaderRoute: typeof HistoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/franchise': {
      id: '/franchise'
      path: '/franchise'
      fullPath: '/franchise'
      preLoaderRoute: typeof FranchiseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/become-relay': {
      id: '/become-relay'
      path: '/become-relay'
      fullPath: '/become-relay'
      preLoaderRoute: typeof BecomeRelayRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/become-driver': {
      id: '/become-driver'
      path: '/become-driver'
      fullPath: '/become-driver'
      preLoaderRoute: typeof BecomeDriverRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin-extras': {
      id: '/admin-extras'
      path: '/admin-extras'
      fullPath: '/admin-extras'
      preLoaderRoute: typeof AdminExtrasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/invest/$id': {
      id: '/invest/$id'
      path: '/$id'
      fullPath: '/invest/$id'
      preLoaderRoute: typeof InvestIdRouteImport
      parentRoute: typeof InvestRoute
    }
  }
}

interface InvestRouteChildren {
  InvestIdRoute: typeof InvestIdRoute
}

const InvestRouteChildren: InvestRouteChildren = {
  InvestIdRoute: InvestIdRoute,
}

const InvestRouteWithChildren =
  InvestRoute._addFileChildren(InvestRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  AdminExtrasRoute: AdminExtrasRoute,
  AuthRoute: AuthRoute,
  BecomeDriverRoute: BecomeDriverRoute,
  BecomeRelayRoute: BecomeRelayRoute,
  DashboardRoute: DashboardRoute,
  FranchiseRoute: FranchiseRoute,
  HistoryRoute: HistoryRoute,
  InboxRoute: InboxRoute,
  InvestRoute: InvestRouteWithChildren,
  InvestDashboardRoute: InvestDashboardRoute,
  OrderRoute: OrderRoute,
  RechargeRoute: RechargeRoute,
  RelayPointsRoute: RelayPointsRoute,
  VerifyRoute: VerifyRoute,
  VtcRoute: VtcRoute,
  VtcDriverRoute: VtcDriverRoute,
  VtcHistoryRoute: VtcHistoryRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
