/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VtcDriverRouteImport } from './routes/vtc-driver'
import { Route as VtcRouteImport } from './routes/vtc'
import { Route as VerifyRouteImport } from './routes/verify'
import { Route as RelayPointsRouteImport } from './routes/relay-points'
import { Route as RechargeRouteImport } from './routes/recharge'
import { Route as OrderRouteImport } from './routes/order'
import { Route as InboxRouteImport } from './routes/inbox'
import { Route as HistoryRouteImport } from './routes/history'
import { Route as FranchiseRouteImport } from './routes/franchise'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as BecomeRelayRouteImport } from './routes/become-relay'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'

const VtcDriverRoute = VtcDriverRouteImport.update({
  id: '/vtc-driver',
  path: '/vtc-driver',
  getParentRoute: () => rootRouteImport,
} as any)
const VtcRoute = VtcRouteImport.update({
  id: '/vtc',
  path: '/vtc',
  getParentRoute: () => rootRouteImport,
} as any)
const VerifyRoute = VerifyRouteImport.update({
  id: '/verify',
  path: '/verify',
  getParentRoute: () => rootRouteImport,
} as any)
const RelayPointsRoute = RelayPointsRouteImport.update({
  id: '/relay-points',
  path: '/relay-points',
  getParentRoute: () => rootRouteImport,
} as any)
const RechargeRoute = RechargeRouteImport.update({
  id: '/recharge',
  path: '/recharge',
  getParentRoute: () => rootRouteImport,
} as any)
const OrderRoute = OrderRouteImport.update({
  id: '/order',
  path: '/order',
  getParentRoute: () => rootRouteImport,
} as any)
const InboxRoute = InboxRouteImport.update({
  id: '/inbox',
  path: '/inbox',
  getParentRoute: () => rootRouteImport,
} as any)
const HistoryRoute = HistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => rootRouteImport,
} as any)
const FranchiseRoute = FranchiseRouteImport.update({
  id: '/franchise',
  path: '/franchise',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const BecomeRelayRoute = BecomeRelayRouteImport.update({
  id: '/become-relay',
  path: '/become-relay',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/auth': typeof AuthRoute
  '/become-relay': typeof BecomeRelayRoute
  '/dashboard': typeof DashboardRoute
  '/franchise': typeof FranchiseRoute
  '/history': typeof HistoryRoute
  '/inbox': typeof InboxRoute
  '/order': typeof OrderRoute
  '/recharge': typeof RechargeRoute
  '/relay-points': typeof RelayPointsRoute
  '/verify': typeof VerifyRoute
  '/vtc': typeof VtcRoute
  '/vtc-driver': typeof VtcDriverRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/auth': typeof AuthRoute
  '/become-relay': typeof BecomeRelayRoute
  '/dashboard': typeof DashboardRoute
  '/franchise': typeof FranchiseRoute
  '/history': typeof HistoryRoute
  '/inbox': typeof InboxRoute
  '/order': typeof OrderRoute
  '/recharge': typeof RechargeRoute
  '/relay-points': typeof RelayPointsRoute
  '/verify': typeof VerifyRoute
  '/vtc': typeof VtcRoute
  '/vtc-driver': typeof VtcDriverRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/auth': typeof AuthRoute
  '/become-relay': typeof BecomeRelayRoute
  '/dashboard': typeof DashboardRoute
  '/franchise': typeof FranchiseRoute
  '/history': typeof HistoryRoute
  '/inbox': typeof InboxRoute
  '/order': typeof OrderRoute
  '/recharge': typeof RechargeRoute
  '/relay-points': typeof RelayPointsRoute
  '/verify': typeof VerifyRoute
  '/vtc': typeof VtcRoute
  '/vtc-driver': typeof VtcDriverRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/auth'
    | '/become-relay'
    | '/dashboard'
    | '/franchise'
    | '/history'
    | '/inbox'
    | '/order'
    | '/recharge'
    | '/relay-points'
    | '/verify'
    | '/vtc'
    | '/vtc-driver'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/auth'
    | '/become-relay'
    | '/dashboard'
    | '/franchise'
    | '/history'
    | '/inbox'
    | '/order'
    | '/recharge'
    | '/relay-points'
    | '/verify'
    | '/vtc'
    | '/vtc-driver'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/auth'
    | '/become-relay'
    | '/dashboard'
    | '/franchise'
    | '/history'
    | '/inbox'
    | '/order'
    | '/recharge'
    | '/relay-points'
    | '/verify'
    | '/vtc'
    | '/vtc-driver'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  AuthRoute: typeof AuthRoute
  BecomeRelayRoute: typeof BecomeRelayRoute
  DashboardRoute: typeof DashboardRoute
  FranchiseRoute: typeof FranchiseRoute
  HistoryRoute: typeof HistoryRoute
  InboxRoute: typeof InboxRoute
  OrderRoute: typeof OrderRoute
  RechargeRoute: typeof RechargeRoute
  RelayPointsRoute: typeof RelayPointsRoute
  VerifyRoute: typeof VerifyRoute
  VtcRoute: typeof VtcRoute
  VtcDriverRoute: typeof VtcDriverRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/vtc-driver': {
      id: '/vtc-driver'
      path: '/vtc-driver'
      fullPath: '/vtc-driver'
      preLoaderRoute: typeof VtcDriverRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vtc': {
      id: '/vtc'
      path: '/vtc'
      fullPath: '/vtc'
      preLoaderRoute: typeof VtcRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/verify': {
      id: '/verify'
      path: '/verify'
      fullPath: '/verify'
      preLoaderRoute: typeof VerifyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/relay-points': {
      id: '/relay-points'
      path: '/relay-points'
      fullPath: '/relay-points'
      preLoaderRoute: typeof RelayPointsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recharge': {
      id: '/recharge'
      path: '/recharge'
      fullPath: '/recharge'
      preLoaderRoute: typeof RechargeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/order': {
      id: '/order'
      path: '/order'
      fullPath: '/order'
      preLoaderRoute: typeof OrderRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inbox': {
      id: '/inbox'
      path: '/inbox'
      fullPath: '/inbox'
      preLoaderRoute: typeof InboxRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/history': {
      id: '/history'
      path: '/history'
      fullPath: '/history'
      preLoaderRoute: typeof HistoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/franchise': {
      id: '/franchise'
      path: '/franchise'
      fullPath: '/franchise'
      preLoaderRoute: typeof FranchiseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/become-relay': {
      id: '/become-relay'
      path: '/become-relay'
      fullPath: '/become-relay'
      preLoaderRoute: typeof BecomeRelayRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  AuthRoute: AuthRoute,
  BecomeRelayRoute: BecomeRelayRoute,
  DashboardRoute: DashboardRoute,
  FranchiseRoute: FranchiseRoute,
  HistoryRoute: HistoryRoute,
  InboxRoute: InboxRoute,
  OrderRoute: OrderRoute,
  RechargeRoute: RechargeRoute,
  RelayPointsRoute: RelayPointsRoute,
  VerifyRoute: VerifyRoute,
  VtcRoute: VtcRoute,
  VtcDriverRoute: VtcDriverRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
